service: billeasy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  # hello:
  #   handler: handler.hello
  #   events:
  #     - httpApi:
  #         path: /
  #         method: get
  employee:
    handler: app/modules/employees.employee
    events:
      - httpApi:
          path: /employee
          method: any
plugins:
  - serverless-offline
